name: Pull request
on:
  pull_request:
jobs:
  rocky9-ovs-aio-test:
    name: aio (Rocky 9 OVS)
    uses: stackhpc/stackhpc-kayobe-config/.github/workflows/stackhpc-all-in-one.yml@parameterise-aio-tests # todo: change after merge
    with:
      kayobe_image: ghcr.io/stackhpc/stackhpc-kayobe-config:stackhpc-2024.1
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovs
      OS_CLOUD: openstack
      openstack_tests_version: ${{ github.ref }}
    secrets: inherit
  ubuntu-jammy-ovn-aio-test:
    name: aio (Ubuntu Jammy OVN)
    uses: stackhpc/stackhpc-kayobe-config/.github/workflows/stackhpc-all-in-one.yml@parameterise-aio-tests # todo: change after merge
    with:
      kayobe_image: ghcr.io/stackhpc/stackhpc-kayobe-config:stackhpc-2024.1
      os_distribution: ubuntu
      os_release: jammy
      ssh_username: ubuntu
      neutron_plugin: ovn
      OS_CLOUD: openstack
      openstack_tests_version: ${{ github.ref }}
    secrets: inherit
