name: Pull request
on:
  pull_request:
jobs:
  build-kayobe-image:
    name: Build Kayobe Image
    uses: stackhpc/stackhpc-kayobe-config/.github/workflows/stackhpc-build-kayobe-image.yml@stackhpc/2024.1

  rocky9-ovs-aio-test:
    name: aio (Rocky 9 OVS)
    uses: stackhpc/stackhpc-kayobe-config/.github/workflows/stackhpc-all-in-one.yml@parameterise-aio-tests # todo: change after merge
    needs: build-kayobe-image
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: rocky
      os_release: "9"
      ssh_username: cloud-user
      neutron_plugin: ovs
      OS_CLOUD: openstack
      openstack_tests_version: ${{ github.ref }}
    secrets: inherit

  ubuntu-jammy-ovn-aio-test:
    name: aio (Ubuntu Jammy OVN)
    needs: build-kayobe-image
    uses: stackhpc/stackhpc-kayobe-config/.github/workflows/stackhpc-all-in-one.yml@parameterise-aio-tests # todo: change after merge
    with:
      kayobe_image: ${{ needs.build-kayobe-image.outputs.kayobe_image }}
      os_distribution: ubuntu
      os_release: jammy
      ssh_username: ubuntu
      neutron_plugin: ovn
      OS_CLOUD: openstack
      openstack_tests_version: ${{ github.ref }}
    secrets: inherit
    
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pip dependencies
        run: pip install -r requirements.txt

      - name: Run pylint
        run: |
          set +e    # disabling exit on non-zero error code so can output warnings without failing
          pylint stackhpc_openstack_tests/*.py
          EXIT_CODE=$?
          set -e
          if [[ $(($EXIT_CODE & 3)) > 0 ]]   #bitwise check for pylint exit codes which indicate errors (01 and 10) https://pylint.readthedocs.io/en/latest/user_guide/usage/run.html#exit-codes
          then
            exit 1
          fi
